name: Android CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    name: Build Android APK
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            openjdk-17-jdk \
            zlib1g-dev

      - name: Install Buildozer & Requirements
        run: |
          pip install --user buildozer==1.5.0
          pip install --user Cython==0.29.36

      - name: Accept Android Licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses

      - name: Build Android APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: http-custom-pro-apk
          path: bin/*.apk
          retention-days: 7
